apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mongodb
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/mongodb-36-rhel7
    importPolicy:
      importMode: Legacy
    name: "3.6"
    referencePolicy:
      type: Source